name: publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      dry-run-only:
        description: "Run xtask publish in dry-run mode (no publish)"
        type: boolean
        required: false
        default: false

jobs:
  publish-cubek-random:
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v5
    with:
      crate: cubek-random
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-cubek-quant:
    needs:
      - publish-cubek-random
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v5
    with:
      crate: cubek-quant
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-cubek-reduce:
    needs:
      - publish-cubek-random
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v5
    with:
      crate: cubek-reduce
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-cubek-matmul:
    needs:
      - publish-cubek-random
      - publish-cubek-reduce
      - publish-cubek-quant
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v5
    with:
      crate: cubek-matmul
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-cubek-convolution:
    needs:
      - publish-cubek-random
      - publish-cubek-reduce
      - publish-cubek-matmul
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v5
    with:
      crate: cubek-convolution
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  publish-cubek-attention:
    needs:
      - publish-cubek-random
      - publish-cubek-reduce
      - publish-cubek-matmul
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v5
    with:
      crate: cubek-attention
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

  
  publish-cubek:
    needs:
      - publish-cubek-random
      - publish-cubek-reduce
      - publish-cubek-matmul
      - publish-cubek-quant
    uses: tracel-ai/github-actions/.github/workflows/publish-crate.yml@v5
    with:
      crate: cubek
      dry-run-only: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run-only || false }}
    secrets:
      CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

